# Generated by Django 3.2 on 2022-06-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
